version: "3.8"

services:
  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana-srvc.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana-rt.entrypoints=web"
      - "traefik.http.routers.grafana-rt.rule=(PathPrefix(`/grafana`))"
      - "traefik.http.routers.grafana-rt.service=grafana-srvc"
