auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

compactor:
  working_directory: /data/loki/compactor
  compaction_interval: 1h
  retention_enabled: true
  retention_delete_delay: 30m
  retention_delete_worker_count: 150
  delete_request_store: filesystem

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 168h
  max_query_lookback: 168h
  split_queries_by_interval: 24h
  max_query_parallelism: 100
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

frontend:
  max_outstanding_per_tenant: 4096
